---

- name: "write approle: {{ approle.role }} to namespace: {{ ns_name }}"
  uri:
    url: "{{ vault_url }}/v1/auth/approle/role/{{ approle.role }}"
    method: POST
    src: "approles/{{ approle.role }}.json"
    headers:
      X-Vault-Token: "{{ lookup('env', 'VAULT_TOKEN') }}"
      X-Vault-Namespace: "{% if ns_name == 'root'%}{% else %}{{ ns_name }}{% endif %}"
    validate_certs: false
    status_code: 204 # 404 = doesnt exist. need to make
