---

- name: "read namespace for {{ ns_name }}"
  uri:
    url: "{{ vault_url }}/v1/sys/namespaces/{{ ns_child }}"
    method: GET
    headers:
      X-Vault-Token: "{{ lookup('env', 'VAULT_TOKEN') }}"
      X-Vault-Namespace: "{{ ns_parent | default('')}}"
    validate_certs: false
    status_code: 200, 404 # 404 yields bad request, already exists
  register: ns_get

# create when ns doesnt exist
- name: "create namespace for {{ ns_name }}"
  uri:
    url: "{{ vault_url }}/v1/sys/namespaces/{{ ns_child }}"
    method: POST
    headers:
      X-Vault-Token: "{{ lookup('env', 'VAULT_TOKEN') }}"
      X-Vault-Namespace: "{{ ns_parent | default('')}}"
    validate_certs: false
    status_code: 200
  when: ns_get.status == 404
  changed_when: true



