---

- name: "create vault policies in {{ ns_name }}"
  command: "{{ vault_bin }}/vault policy write {{ policy }} policies/{{ policy | replace(' ','')}}.hcl"
  environment:
    VAULT_ADDR: "{{ vault_url }}"
    VAULT_NAMESPACE: "{% if ns_name == 'root' %}{% else %}{{ ns_name | default('')}}{% endif %}"
