---

- name: "create vault policies in {% if ns_name == 'root' %}{% else %}{{ ns_name | default('')}}{% endif %}"
  hashivault_policy_set_from_file:
      name: "{{ policy }}"
      rules_file: "{{ playbook_dir }}/policies/{{ policy | replace(' ','') }}.hcl" # remove spaces when list item contains
      namespace: "{% if ns_name == 'root' %}{% else %}{{ ns_name | default('')}}{% endif %}"