---

- name: "create vault policies in {{ ns_name }}"
  hashivault_policy_set_from_file:
      name: "{{ policy }}"
      rules_file: "{{ playbook_dir }}/policies/{{ policy | replace(' ','') }}.hcl" # remove spaces when list item contains
      namespace: "{{ ns_name }}"
