---

# Requirements:
#
# file: config/namespaces.yml

# TODO: account for spaces
# TODO: pki backend
# TODO: plugins
# TODO: idempotence on policy plays

- hosts: localhost
  strategy: linear
  run_once: true
  connection: local
  vars_files:
    - "{{ playbook_dir }}/config/{{ namespace_config_file }}"
  tasks:

    - set_fact:
        ns_list: "{{ namespace_config.keys() | list }}"
        ns_config: "{{ namespace_config }}"

    - name: iterate through ns_nest to create parent / child namespaces
      include_role:
        name: namespace
      loop: "{{ ns_list }}"
      loop_control:
        loop_var: ns_name
      vars:
        approles: "{{ ns_config[ns_name].approles | default([])}}"
        ldap: "{{ ns_config[ns_name].ldap }}"
        engines: "{{ ns_config[ns_name].engines | default([]) }}"
        policies: "{{ ns_config[ns_name].policies | default('default') }}"
        associations: "{{ ns_config[ns_name].associations | default('') }}"

