---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: instance
    image: drewmullen/docker-vault-ent:1.2.2
    pre_build_image: true
    command: server -dev && sleep 10000
    override_command: true
    published_ports:
      - 0.0.0.0:8200:8200/tcp
    env:
      VAULT_DEV_ROOT_TOKEN_ID: root
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    options:
      exclude:
        - roles/namespace/tasks/_policy_associate.yml
      x:
        - "602"
verifier:
  name: testinfra
  lint:
    name: flake8
scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - syntax
    - create
    - converge
    - verify
    - cleanup
    - destroy
