---
# - name: Converge
#   hosts: all
#   roles:
#     - role: namespaces

- hosts: localhost
  strategy: linear
  run_once: true
  connection: local
  vars:
    namespace_config_file: "/Users/dmullen/git/ansible-vault-namespaces/config/namespaces_config.yml"
  tasks:

    - name: ingest namespace config file
      include_vars: "{{ namespace_config_file }}"

    - name: parse namespace configs
      set_fact:
        ns_list: "{{ namespace_config.keys() | sort }}"
        ns_config: "{{ namespace_config }}"

    - name: iterate through ns_list to create parent / child namespaces
      include_role:
        name: /Users/dmullen/git/ansible-vault-namespaces/roles/namespace
      loop: "{{ ns_list }}"
      loop_control:
        loop_var: ns_name
      vars:
        auths: "{{ ns_config[ns_name].auths | default([]) }}"
        engines: "{{ ns_config[ns_name].engines | default([]) }}"
        policies: "{{ ns_config[ns_name].policies | default('default') }}"
        # associations: "{{ ns_config[ns_name].associations | default([]) }}" currently disabled
